const phrases = {
    amigo: "pana",
    delator: "pajúo",
    pertenencias: "Macundales",
    elegir: "Deja el culipandeo",
    flojera: "caligueva",
    molestia: "Es una ladilla",
    situacion_confusa: "Es un arroz con mango",
    fuera_de_control: "Se formó un cojeculo",
    vengare: "Lo agarro en la bajaíta",
    buenisimo: "Está arrecho",
    oportunista: "Tú si eres arrecho",
    dificilisimo: "Eso está arrecho",
    molesto: "Está arrecho",
    mentiroso: "Eres mojonero",
    miedoso: "Eres un culillúo",
    nino: "Muchacho er coño",
    child: "guaricho",
    boy: "chamo/chama",
    maduro: "El coño e tu madre!",
    alto_rango: "El chivo que más mea",
    alto_intelecto: "caja de machete",
    esfuerzo: "Echarle pichón / Echarle bolas",
    poner_esfuerzo: "Le echaste bolas",
    contactos: "enchufao",
    creido: "mojoniao",
    despistado: "Aguevoniao",
    equivocado: "Está meando fuera del perol",
    muy_bien: "Te quedó de pinga / Te la comiste",
    desaparecido: "Dejó la peluca",
    rapido: "Va esmojonao",
    amanerado: "Tiene un meneíto raro / está rullío 'e ratón",
    homosexual: "Es marico / Es pargo",
    seriedad: "Deja la guachafita",
    espero_que_no: "Sape gato",
    no_tocar: "Jorúngate el culo",
    preste_atencion: "Párame bola",
    muy_lejos: "Eso queda en el quinto coño",
    muy_junto: "Eso está amuñuñao",
    no_te_creo: "Siiii Luiiis",
    desentendido: "se hace el loco / se hace el Willy Meys",
}
Object.keys(phrases).forEach(id => {
    document.getElementById(id).addEventListener('click', () => {
        document.getElementById('resultado').innerText = phrases[id];
    });
});