const phrases = {
    "Adulador":"Jalabola",
    "Amigo": "Pana",
    "Chico / Chica": "Chamo / Chama",
    "Creído": "Mojoniao",
    "Delator": "Pajúo",
    "Despistado": "Aguevoniao",
    "Despreocupado":"Antiparabólico",
    "Esforzarse": "Echarle pichón / Echarle bola",
    "Flojera": "Caligüeva",
    "Mezquino": "Pichirre",
    "Niño": "Guaricho",
    "Pertenencias": "Macundales",
    "Vigilante": "Guachimán",
    "Acción de adular":"Jalabolismo",
    "Anda a molestar a otro lugar": "Zapatea pa otro lado",
    "Basta con eso": "Sácamelo",
    "Corre muy rapido": "Va esmojonao",
    "Creo que es hora de partir":"¿Y si hacemos como que nos vamos?",
    "Debes elegir": "Deja el culipandeo",
    "El sol está intenso":"Está haciendo la pepa'e sol",
    "Es homosexual": "Es marico / Es pargo",
    "Es una molestia": "Es una ladilla",
    "Es una situacion confusa": "Es un arroz con mango",
    "Espero que eso no suceda": "Sape gato",
    "Está muy difícil": "Eso está arrecho",
    "Está molesto": "Está arrecho",
    "Eres un mentiroso": "Eres mojonero",
    "Eres un miedoso": "Eres un culillúo",
    "Eso está buenisimo": "Está arrecho",
    "Eso está muy bueno": "Eso está de pinga",
    "Eso está muy lejos": "Eso queda en el quinto coño",
    "Eso está muy junto": "Eso está amuñuñao",
    "Estoy cansado": "Estoy mamao",
    "Estoy de acuerdo":"De bola",
    "Ha fallecido":"Peló bola",
    "Hace todo bien":"Es un vergatario",
    "Le han estafado":"Le metieron un paquete chileno",
    "Le pusiste empeño / Lo lograste": "Le echaste bolas",
    "Lo han robado":"Lo tumbaron",
    "Lo haré":"Sí va",
    "Distancia incierta":"Allaíta",
    "Llueve a cántaros":"Está cayendo un palo de agua",
    "Me vengare": "Lo agarro en la bajaíta",
    "Mi situación económica es precaria":"Estoy pelando bola",
    "Nicolás Maduro": "El coño e tu madre!",
    "Niño inquieto": "Muchacho er coño",
    "No deja usted ver":"Carne de burro no es trasparente",
    "No entendí lo que has dicho":"La tuya, por si acaso",
    "No me importa":"Me sabe",
    "No quites las hojas a las plantas":"Arráncate los pelos del culo",
    "No sea entrometido":"Echale Sal!",
    "No te creo nada": "Siiii Luiiis",
    "No te lo permitiré": "Me lo vas a mamar",
    "No tengo dinero":"Estoy mamando y loco",
    "No toque eso": "Jorúngate el culo",
    "Nos apartamos del sol":"Mamá no parió teja",
    "Otra vez con lo mismo?": "Vas a seguir Abigail?",
    "Préstame atencion": "Párame bola",
    "Persona con contactos": "Enchufao",
    "Persona de alto rango": "El chivo que más mea",
    "Persona de alto intelecto": "Caja de machete",
    "Se fue muy rápido": "Dejó la peluca",
    "Se ha confundido":"Se volvió un culo",
    "Se ha cumplido tu predicción":"Boca 'e sapo",
    "Se ha desmayado":"Le dio un yeyo",
    "Se hace el desentendido": "Se hace el loco / Se hace el Willie Mays",
    "Se salió de control": "Se formó un cojeculo",
    "Su pareja le ha engañado":"Le soplaron el bistec",
    "Su pareja le ha terminado":"Lo mandaron pal coño",
    "Te destruiré":"Te via jodé",
    "Te ha quedado muy bien": "Te quedó de pinga / Te la comiste",
    "Te haces pasar por dulce y afectiva":"Dulcito el mamón",
    "Tiene gestos amanerados": "Está rullío 'e ratón",
    "Toma las cosas con seriedad": "Deja la guachafita",
    "Usa la tarjeta de crédito":"Raspa la tarjeta",
    "Usted es un atrevido": "Tú si eres arrecho",
    "Usted es muy bueno en lo que hace": "Usted es un arrecho",
    "Usted está en peligro": "Estás en pico 'e zamuro",
    "Usted está equivocado": "Está meando fuera del perol",
}

let boton = document.createElement("button");
for (const [key, value] of Object.entries(phrases)) {
    boton = document.createElement("button");
    boton.id = key;
    // insertar texto de objeto frases en el boton.
    boton.innerText = key;
    document.querySelector(".botones").appendChild(boton);
}

Object.keys(phrases).forEach(id => {
    document.getElementById(id).addEventListener('click', () => {
        document.getElementById('resultado').innerText = phrases[id];
    });
});